### ISSUE TITLE
Investigate number and type of records deleted from hbz01

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#258]
Some records from hbz union catalogue (hbz01) are deleted and deletions are recorded in the XML clobs we receive. Unfortunately, the deletions are only associated with the internal Aleph ID not the hbz ID.

Currently, we don't do anything with deletions, i.e. the records continue to exist unchanged in lobid after a deletion from the union catalogue. As we don't have a lookup table Aleph-ID->hbz ID we can't even find out which records were deleted in the past.

The easiest way to find out about deleted records is when we get a new full dump of the database. We would just have to look which records are in lobid that aren't in the union catalogue.Thus, after receiving the next full dump we will explore how many deleted records are still in lobid and of what kind these are. After that we have to decide how we will handle deletions in lobid...

**Comment by acka47** [comment]
> Currently, we don't do anything with deletions, i.e. the records continue to exist unchanged in lobid after a deletion from the union catalogue. As we don't have a lookup table Aleph-ID->hbz ID we can't even find out which records were deleted in the past.

What is the status for 2.0 on this, @dr0i ? I guess deletions aren't considered with daily updates but are taken into account twice a week with full dump indexing, right?

**Comment by dr0i** [comment]
Right.

**Comment by acka47** [comment]
As we index a full dump each week end this issue isn't actually a problem anymore, as deleted records will be removed from lobid latest five days after their deletion. Closing.

**Comment by dr0i** [comment]
Customers asked of this feature so we should somehow implement it.
Reopening.

**Comment by dr0i** [comment]
How shall we implement this? 

a) Would it be enough to retain the deletion-marks only for about one week? Background: every week a complete new index is build, based upon fresh data, which will not contain any deletions. ~These would be overwritten.~ As a new basedump _has no deletions at all_  there is no way to keep record of deletions older than the last full-basedump ETL.

b)We could also build a new "deletion"-index which would store _all_ the deleted data. We could then at our will decide when to clean that "deletion"-index. This index would have it's own , simple lookup-API.

In both cases we need to store the internal `sys`-number of course. We could index  that field and exclude it from being displayed ("_source excluded") when going with a). Going with b) I wouldn't have any considerations not to overtly display an internal id because this "deletion"-index would only be used by "insiders" anyhow, at least not by any "normal" web app.

a) has also the disadvantage to be forced to clean the deleted-data (except for the deltion marks and the deletion date)  so that normal api-queries don't result in outdated data. Going with b) we could even retain the complete old data. This might be interesting, e.g. one could create an view of all the verbundkatalog-resources which are expelled from that database (if that _would_ be so easy ... I could imagine that most of the deletions are doublettes and such things.) 

What do you think - a or b ?

**Comment by acka47** [comment]
There is at least one other option we should consider:

c) Replace JSON-LD description of deleted resources by deletion information, e.g. something like this:

```json
{
  "id":"http://lobid.org/resources/HT1234567#!",
  "describedBy":{
    "dateCreated":"19900611",
    "dateDeleted":"20180202",
    "id":"http://lobid.org/resources/HT1234567",
    "label":"lobid Ressource",
    "deletedBy":{
      "id":"http://lobid.org/organisations/DE-ex#!",
      "label":"lobid Organisation"
    },
    "sourceOrganization":{
      "id":"http://lobid.org/organisations/DE-ex3#!",
      "label":"lobid Organisation"
    }
  }
}
```
I don't know whether we actually get information on the institution that caused the deletion. If not, `deletedBy` would be omitted.

**Comment by dr0i** [comment]
Yeah that's what I meant with a) (among other details I noted there).

**Comment by acka47** [comment]
Then I am for a) plus keeping the information longer which is c) and maybe even what you meant with b). :-)

**Comment by dr0i** [comment]
this needs a telephone call.

**Comment by dr0i** [comment]
ping @hagbeck

**Comment by dr0i** [comment]
ping @hagbeck.

**Comment by dr0i** [comment]
I updated my question of "a) vs b)" a bit. I'll go with b) and use your proposal regarding data-modelling (aka "c)").

**Comment by dr0i** [comment]
Documentation at http://lobid.org/deletions.

**Comment by ChristophEwertowski** [comment]
The text looks good. I don't think that we need it in German as developers should understand the English text. 
But the block "resources" seems to be selected although it isn't. Also the block "hbz01-AlephMabXml" doesn't work as there is no startpage for hbz01.

**Comment by acka47** [comment]
+1 How public and "official" should this API be? We should at least announce this via the mailing list maybe even with a blog post.

**Comment by acka47** [comment]
Discussing this offline, we came to the conclusion that it would be better to include this functionality (to query for a list of deleted resources in a specific time frame) in the lobid-resources API instead of adding a separate service. For example, a client would query something like `https://lobid.org/resources/search?deleted=20180328-20180403` and gets all deleted resources in the specified timeframe.

**Comment by dr0i** [comment]
Deployed to staging for testing. Querying a specified timeframe is possible with a simple elasticsearch query. This is very straightforward because you query what you see (WYSIWYQ), like this: `http://stage.lobid.org/resources/deletions/search?q=describedBy.deleted:>201803028+AND+describedBy.deleted:<20180405&size=3`. Only two parameters are supported: `q` for the query and `size` for the result size.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
So - ready to inform customers. Assigning @acka47 .

**Comment by dr0i** [comment]
pinging @hagbeck for testing

**Comment by dr0i** [comment]
Mail sent to customers, closing.

**Comment by dr0i** [comment]
Fyi, changes in the API: https://github.com/hbz/lobid-resources/issues/801.
