### ISSUE TITLE
A significant number of maps aren't classified as such

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#373]
Querying for http://test.lobid.org/resource?name=karte I found several maps that are not rdf:type bibo:Map. Examples:

[HT009578713](http://lobid.org/resource/HT009578713/about), [HT007640033](http://lobid.org/resource/HT007640033), [CT003053572](http://lobid.org/resource/CT003053572), [BT000141043](http://lobid.org/resource/BT000141043/about), [BT000089522](http://lobid.org/resource/BT000089522), [BT000077891](http://lobid.org/resource/BT000077891)

We probably have to do some more work on this.

**Comment by dr0i** [comment]
Seems to be resolved. Have a look @acka47 .

**Comment by acka47** [comment]
Nope, isn't resolved. All named (and now linked resources) are in fact maps but still the RDF doesn't contain the triple `<> rdf:type bibo:Map .`

**Comment by ChristophEwertowski** [comment]
In the current json files they aren't typed as bibo:Map because 050[plane 10] doesn't exist in these resources, e.g. they aren't named as "Landkarte". Some extent statements tell that it is a map but that can not be found in all of the resources. Because of the small number of the affected resources it should be done in the Aleph client. Added it to the corresponding [issue](https://github.com/hbz/lobid-resources/issues/258). Closing.
