### ISSUE TITLE
Fulltext links missing in RDF

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#489]
Examples:
- http://lobid.org/resource/ZDB2232704-6/about: Only one fulltextOnline-Link is shown though three exist in field 655e in the source data. 
- http://lobid.org/resource/HT014995973/about No fulltext link shown though two exist in source data.
- http://lobid.org/resource/HT014144676/about

**Comment by acka47** [comment]
Many of these are solved with https://github.com/lobid/lodmill/issues/700 – but not all.

E.g. for http://lobid.org/resource/HT014995973/about one link is shown (one that doesn't work) while the second link (that does work) isn't part of the RDF.

**Comment by acka47** [comment]
Another example from a duplicate issue (https://github.com/hbz/lobid/issues/85): 

http://lobid.org/resource/HT014063180/about Here as well one link that doesn't work is part of the RDF while another – working – link wasn't transformed to the RDF though it is in the source data.

**Comment by acka47** [comment]
Fixed in 2.0 for http://lobid.org/resources/HT014720195 but the other three resources have still no fulltextOnline link, see http://lobid.org/resources/HT014995973, http://lobid.org/resources/HT014144676 and http://lobid.org/resources/HT011170551.

**Comment by ChristophEwertowski** [comment]
Changed the definition for `@fulltextOnlineUri` so that keywords in `655e1.[x3]` don't have to start with the three letter combinations but contain the words. Because of that HT019011249 looses a link to a fulltext because `655e1.3` contains "Voltext", not "Volltext" ([HT019011249 (hbz01)](http://lobid.org/hbz01/HT019011249)). Also all URIs are accepted if they contain an DOI or URN link, regardless if they meet the listed keywords.
Otherwise I expanded the definitions for the labels of URNs. Now the label only has to contain "nbn-resolving.de/urn" to get the label `URN-Link`. See [HT003536695 (production)](http://lobid.org/resources/HT003536695.json) / [HT003536695 (test)](http://test.lobid.org/resources/HT003536695.json) for just the right label, [HT016618741 (production)](http://lobid.org/resources/HT016618741.json) / [HT016618741 (test)](http://test.lobid.org/resources/HT016618741.json) for a new fulltextOnline URN link and [HT018468645 (production)](http://lobid.org/resources/HT018468645.json) / [HT018468645 (test)](http://test.lobid.org/resources/HT018468645.json) for right label (property `similar`) and new fulltextOnline DOI link.
These changes should change HT014995973 and HT014144676 too but I'm not adding them to keep the test set small. HT011170551 however won't be covered but this commit. It would be covered if the librarian had added the URN from the linked website.

Update: The links only worked at production. After a pull request of a new version of the play application "HT0123456.json" works too.

**Comment by acka47** [comment]
+1
