### ISSUE TITLE
Library with two addresses

### ISSUE THREAD

**Issue by peterreimer** [lobid/lodmill#659]
Is this a valid entry: two addresses, but only one set of geo coordinates?
http://lobid.org/organisation/DE-1393-BOT/about

**Comment by acka47** [comment]
This is a known issue, see https://github.com/lobid/lodmill/issues/486 which we won't fix in this version of lobid organisations. Generally, we want to switch to http://beta.lobid.org/organisations in the future where this issue doesn't occur. Unfortunately, the [entry for DE-1393-BOT in beta organisations]() looks quite broken, only having one address that doesn't have much to do with one of the actual addresses... Will open a separate issue for this.

**Comment by peterreimer** [comment]
OK. Since it seems to be a duplicate, i close this issue.

**Comment by philboeselager** [comment]
Just a post-closing note: the address "Mellinghofer Str. 55" in "Mülheim" is simply wrong here, since the name of this organization is "Zweigbibliothek Bottrop".
Altough being speculative, I could imagine that these organizations got merged because all chunks of the one address occur as complete chunks in the other one (only appended by "-BOT" as an additional chunk).
