### ISSUE TITLE
Adjust transformation of field 200 subfield h

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#773]
> Regarding 
>> http://lobid.org/nwbib/BT000082463 Mitwirkung [HBZ01-Feld 200 *b*]: 
>> Sozialdemokratische Partei Deutschland. Ortsverein à es fehlt die 
>> Anzeige des Unterfeld *h* Warendorf

> the problem is that the content of subfield `h` is wrapped in angle brackets (`<>`) which is the reason that it is not seen in the browser.

We will go for this solution:

> Adjust [line 828 in the current morph](https://github.com/lobid/lodmill/blob/9710b449d88e981dc8080e2a9327a1c4dc5f1966/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L828) to use normal brackets (`()`) instead of angele brackets.

**Comment by dr0i** [comment]
As we agreed that we use the index build with the new hbz/lobid-resources repo for now for getting displaying data AND this issue is a display issue it will be treated in the mentioned new repo.

**Comment by dr0i** [comment]
Deployed to index-2.0, see gaia.hbz-nrw.de:9200/resources/resource/BT000082463 .
If @acka47 gives his ok, @fsteeg can grab that index' document to build the nwbib-view.

**Comment by dr0i** [comment]
Correction: as this issued was treated by both repo's (lobid/lodmill AND hbz/lobid-resources) there is nothing to do for @fsteeg.

**Comment by acka47** [comment]
I still see angle brackets, thus, re-assigned @dr0i .

**Comment by dr0i** [comment]
Uh. You're right, I was confused because:

a) the subject of this issue is a bit vacuous
b) there is a ticket (#774) with a subject that exactly tells me to do what #773 is about (I would say #774 shouldn't have been opened in the first place and the subject of 773 should be that of #774)
c) actually, http://lobid.org/nwbib/BT000082463 does show the (once) missing "Warendorf"
d) a week lays between my last working on this

Now I remember: https://github.com/lobid/lodmill/pull/774#issuecomment-179237771  does apply to this ticket #773. So there will be only one solution in one repo (the new one). Indexing is running since 4 hours and will be finished in further 8 hours.

**Comment by dr0i** [comment]
Deployed to small test set into index 2.0, see e.g. http://gaia.hbz-nrw.de:9200/resources-staging/resource/BT000082463.

**Comment by acka47** [comment]
I didn't remember all this as well (having opened a pull request myself etc.). However, looks good now in "data 2.0". +1

**Comment by dr0i** [comment]
Deployed in full index, closing.

**Comment by dr0i** [comment]
Data exists in index 2.0 at gaia. Now you can lookup that index to use the labels in the frontend.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/BT000082463

**Comment by acka47** [comment]
> Deployed to staging: http://test.lobid.org/nwbib/BT000082463

+1 (I also can see the text wrapped in angle brackets on production now. However, normal brackets are mor euser-friendly I guess.)
